version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      - USER=nozomi
    tty: true

  db:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data